version: '3'
services:
  react-app:
    build: ./client
    stdin_open: true
    restart: always
    ports:
      - '3000:3000'
    networks:
      - mern-app
  api-server:
    build: ./
    env_file:
      - .env
    environment:
      - MONGO_URL=${MONGO_URL}
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    networks:
      - mern-app
  mongo:
    image: mongo
    expose:
      - '27017'
    ports:
      - '27017:27017'
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
